name: 'quiet_companion'
version: '1.0.0'
config-version: 2

profile: 'quiet_companion'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  quiet_companion:
    +materialized: view
    account:
      +schema: account
    advisor:
      +schema: advisor
    client:
      +schema: client
    holdings:
      +schema: holdings
    transactions:
      +schema: transactions
  elementary:
    +schema: elementary

seeds:
  quiet_companion:
    schema: seeds