version: 2

sources:
  - name: quiet_companion
    schema: raw
    tables:
      - name: raw_accounts
        description: "Raw accounts data"
        columns:
          - name: effective_date
            data_tests:
              - not_null
          - name: account_number
            data_tests:
              - not_null
          - name: ssn
            data_tests:
              - not_null
          - name: account_type
            data_tests:
              - not_null
          - name: account_status
            data_tests:
              - not_null
          - name: date_opened
            data_tests:
              - not_null
      - name: raw_client
        description: "Raw client information"
        columns:
          - name: effective_date
            data_tests:
              - not_null
          - name: ssn
            data_tests:
              - not_null
              - unique
          - name: first_name
            data_tests:
              - not_null
          - name: last_name
            data_tests:
              - not_null
          - name: date_of_birth
            data_tests:
              - not_null
      - name: raw_client_address
        description: "Raw client address data"
        columns:
          - name: effective_date
            data_tests:
              - not_null
          - name: ssn
            data_tests:
              - not_null
              - unique
          - name: address_line_1
            data_tests:
              - not_null
          - name: city
            data_tests:
              - not_null
          - name: state
            data_tests:
              - not_null
          - name: zip_code
            data_tests:
              - not_null
