CREATE TABLE quiet_companion.raw.raw_trades (
    effective_date TEXT,
    trade_id TEXT,
    account_number TEXT,
    ssn TEXT,
    advisor_code TEXT,
    advisor_name TEXT,
    trade_date TEXT,
    settlement_date TEXT,
    asset_class TEXT,
    ticker TEXT,
    security_name TEXT,
    "action" TEXT,
    quantity TEXT,
    price TEXT,
    gross_amount TEXT,
    commission TEXT,
    net_amount TEXT,
    currency TEXT,
    trade_status TEXT,
    order_type TEXT,
    account_type TEXT,
    tax_status TEXT,
    notes TEXT,
    raw_created_timestamp TIMESTAMP
);
