name: 'quiet_companion'
version: '1.0.0'
config-version: 2

profile: 'quiet_companion'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  quiet_companion:
    +materialized: view
  elementary:
    +schema: "{{ target.schema }}"

seeds:
  quiet_companion:
    schema: quiet_companion_seeds