CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS typ;
CREATE SCHEMA IF NOT EXISTS cls;
CREATE SCHEMA IF NOT EXISTS elementary;
CREATE SCHEMA IF NOT EXISTS seeds;
CREATE SCHEMA IF NOT EXISTS flyway;
